#!/bin/bash

srcrundir=${1-../fcst}
destdir=${2-./}

srcabsdir=$(realpath $srcrundir)
destabsdir=$(realpath $destdir)
srcabsdir=${srcabsdir##/mnt}
destabsdir=${destabsdir##/mnt}

echo ""
echo "SRCDIR: $srcabsdir"
echo "DESDIR: $destabsdir"
echo ""

if [[ ! -r $destabsdir ]]; then
    mkdir -p $destabsdir
fi

cd $destabsdir || exit 0

#
# find symbolic files
#
linkfiles=()
while IFS='' read -r line; do linkfiles+=("$line"); done < <(find $srcabsdir -type l)
#linkfiles=($(find $srcabsdir -type l))

echo "Linking symbolic files ..."
for fn in "${linkfiles[@]}"; do
    #echo "$fn -> $(readlink $fn)"
    echo "Linking $(basename $fn) ..."
    ln -sf $(realpath $fn) $(basename $fn)
done

#
# Hard copy some files
#

if [[ -f $srcabsdir/run_mpas.slurm ]]; then
    jobfile="run_mpas.slurm"
elif [[ -f $srcabsdir/run_mpas.pbs ]]; then
    jobfile="run_mpas.pbs"
else
    jobfile="none"
fi

cpfiles=(namelist.atmosphere streams.atmosphere          \
         stream_list.atmosphere.output stream_list.atmosphere.surface)


for fn in "${cpfiles[@]}"; do
    echo "Copying $fn ..."
    cp $srcabsdir/$fn .
done

cpanyone=(stream_list.atmosphere.diagnostics stream_list.atmosphere.diagnostics_fcst stream_list.atmosphere.diagnostics_da )
for fn in "${cpanyone[@]}"; do
   if [[ -e $fn ]]; then
       echo "Copying $fn ..."
       cp $srcabsdir/$fn .
   fi
done

#
# for ICs/LBCs
#
if compgen -G "*.init.nc" > /dev/null; then
    :
else
    if compgen -G "$srcabsdir/*.init.nc" > /dev/null; then
        ln -sf $srcabsdir/*.init.nc .
    fi
fi

if compgen -G "*.lbc*.nc" > /dev/null; then
    :
else
    ln -sf $srcabsdir/*.lbc.*.nc .
fi

if compgen -G "*.graph.info.part.*" > /dev/null; then
    :
else
    ln -sf $srcabsdir/*.graph.info.part.* .
fi

#
# Modify job script
#
if [[ ! "${jobfile}" == "none" ]]; then
    echo "Copying ${jobfile} ..."
    cp $srcabsdir/${jobfile} .

    echo "Modify dirname in \"$jobfile\" ..."
    sed -i "s#$srcabsdir#$destabsdir#g" $jobfile
fi

exit 0
